//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 

namespace VB.Common.Core.Utilities.PDF
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "PrinceXmlWebServiceSOAP", Namespace = "http://www.VB.biz/service/PrinceXml/v1")]
    public partial class PrinceXmlWebServiceProxy : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback generateOperationCompleted;

        /// <remarks/>
        public PrinceXmlWebServiceProxy()
        {
            this.Url = "https://www.VB.biz/VB-queue-ws/services/PrinceXmlWebService";
        }

        public PrinceXmlWebServiceProxy(string url)
        {
            this.Url = url;
        }

        /// <remarks/>
        public event generateCompletedEventHandler generateCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://www.VB.biz/VB-queue-ws/services/PrinceXmlWebService/generat" +
            "e", RequestElementName = "PrinceXmlRequest", RequestNamespace = "http://www.VB.biz/service/PrinceXml/v1", ResponseElementName = "PrinceXmlResponse", ResponseNamespace = "http://www.VB.biz/service/PrinceXml/v1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Status")]
        public Status generate(Input Input, OutputType OutputType, out Output Output)
        {
            object[] results = this.Invoke("generate", new object[] {
                    Input,
                    OutputType});
            Output = ((Output)(results[1]));
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult Begingenerate(Input Input, OutputType OutputType, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("generate", new object[] {
                    Input,
                    OutputType}, callback, asyncState);
        }

        /// <remarks/>
        public Status Endgenerate(System.IAsyncResult asyncResult, out Output Output)
        {
            object[] results = this.EndInvoke(asyncResult);
            Output = ((Output)(results[1]));
            return ((Status)(results[0]));
        }

        /// <remarks/>
        public void generateAsync(Input Input, OutputType OutputType)
        {
            this.generateAsync(Input, OutputType, null);
        }

        /// <remarks/>
        public void generateAsync(Input Input, OutputType OutputType, object userState)
        {
            if ((this.generateOperationCompleted == null))
            {
                this.generateOperationCompleted = new System.Threading.SendOrPostCallback(this.OngenerateOperationCompleted);
            }
            this.InvokeAsync("generate", new object[] {
                    Input,
                    OutputType}, this.generateOperationCompleted, userState);
        }

        private void OngenerateOperationCompleted(object arg)
        {
            if ((this.generateCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.generateCompleted(this, new generateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [Serializable()]
    [DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.VB.biz/service/PrinceXml/v1")]
    public partial class Input
    {

        private ContentType contentTypeField;

        private string contentField;

        private string[] styleSheetPathsField;

        /// <remarks/>
        public ContentType ContentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
            }
        }

        /// <remarks/>
        public string Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StyleSheetPaths")]
        public string[] StyleSheetPaths
        {
            get
            {
                return this.styleSheetPathsField;
            }
            set
            {
                this.styleSheetPathsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [Serializable()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.VB.biz/service/PrinceXml/v1")]
    public enum ContentType
    {

        /// <remarks/>
        Html,

        /// <remarks/>
        Xml,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [Serializable()]
    [DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.VB.biz/service/PrinceXml/v1")]
    public partial class Output
    {

        private OutputTypeCode outputTypeCodeField;

        private object itemField;

        /// <remarks/>
        public OutputTypeCode OutputTypeCode
        {
            get
            {
                return this.outputTypeCodeField;
            }
            set
            {
                this.outputTypeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ByteStream", typeof(byte[]), DataType = "hexBinary")]
        [System.Xml.Serialization.XmlElementAttribute("FilePathRelativeToSharedFileSystemRoot", typeof(string))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [Serializable()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.VB.biz/service/PrinceXml/v1")]
    public enum OutputTypeCode
    {

        /// <remarks/>
        ByteStream,

        /// <remarks/>
        SharedFileSystem,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [Serializable()]
    [DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.VB.biz/service/PrinceXml/v1")]
    public partial class Status
    {

        private StatusCode codeField;

        private string messageField;

        /// <remarks/>
        public StatusCode Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [Serializable()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.VB.biz/service/PrinceXml/v1")]
    public enum StatusCode
    {

        /// <remarks/>
        Success,

        /// <remarks/>
        ClientError,

        /// <remarks/>
        ServerError,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [Serializable()]
    [DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.VB.biz/service/PrinceXml/v1")]
    public partial class SharedFileSystem
    {

        private string filePrefixField;

        private string fileSuffixField;

        private string directoryPathRelativeToSharedFileSystemRootField;

        /// <remarks/>
        public string FilePrefix
        {
            get
            {
                return this.filePrefixField;
            }
            set
            {
                this.filePrefixField = value;
            }
        }

        /// <remarks/>
        public string FileSuffix
        {
            get
            {
                return this.fileSuffixField;
            }
            set
            {
                this.fileSuffixField = value;
            }
        }

        /// <remarks/>
        public string DirectoryPathRelativeToSharedFileSystemRoot
        {
            get
            {
                return this.directoryPathRelativeToSharedFileSystemRootField;
            }
            set
            {
                this.directoryPathRelativeToSharedFileSystemRootField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [Serializable()]
    [DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.VB.biz/service/PrinceXml/v1")]
    public partial class OutputType
    {

        private OutputTypeCode outputTypeCodeField;

        private SharedFileSystem itemField;

        /// <remarks/>
        public OutputTypeCode OutputTypeCode
        {
            get
            {
                return this.outputTypeCodeField;
            }
            set
            {
                this.outputTypeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SharedFileSystem")]
        public SharedFileSystem Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void generateCompletedEventHandler(object sender, generateCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [DebuggerStepThrough()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class generateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal generateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState)
            :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public Status Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Status)(this.results[0]));
            }
        }

        /// <remarks/>
        public Output Output
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Output)(this.results[1]));
            }
        }
    }
}