//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VB.Common.ActiveRecord {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ActiveRecord {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActiveRecord() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VB.Common.ActiveRecord.ActiveRecord", typeof(ActiveRecord).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received {0} rows but expected {1} rows.
        /// </summary>
        internal static string Finder_Bad_Row_Count {
            get {
                return ResourceManager.GetString("Finder_Bad_Row_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of rows affected but expected {1}.
        /// </summary>
        internal static string ManyToMany_Bad_Delete_Count {
            get {
                return ResourceManager.GetString("ManyToMany_Bad_Delete_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed 1 item from the collection that was not in the DB..
        /// </summary>
        internal static string ManyToMany_Collection_Remove_NonMember {
            get {
                return ResourceManager.GetString("ManyToMany_Collection_Remove_NonMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed 1 item from the DB that was not in the collection..
        /// </summary>
        internal static string ManyToMany_Db_Remove_NonMember {
            get {
                return ResourceManager.GetString("ManyToMany_Db_Remove_NonMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of rows affected but expected {1}.
        /// </summary>
        internal static string RowDataGateway_Bad_Update_Count {
            get {
                return ResourceManager.GetString("RowDataGateway_Bad_Update_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} has {0} primary key (IdAttribute) columns.
        /// </summary>
        internal static string RowDataGateway_Duplicate_IdAttribute {
            get {
                return ResourceManager.GetString("RowDataGateway_Duplicate_IdAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} has declared a property {1} with an IdAttribute but not a ColumnAttribute.
        /// </summary>
        internal static string RowDataGateway_Incomplete_IdAttribute {
            get {
                return ResourceManager.GetString("RowDataGateway_Incomplete_IdAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} of type {1} does not have a ColumnAttribute..
        /// </summary>
        internal static string RowDataGateway_Missing_ColumnAttribute {
            get {
                return ResourceManager.GetString("RowDataGateway_Missing_ColumnAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} has not declared a property with an IdAttribute.
        /// </summary>
        internal static string RowDataGateway_Missing_IdAttribute {
            get {
                return ResourceManager.GetString("RowDataGateway_Missing_IdAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} has no TableAttribute annotation.
        /// </summary>
        internal static string RowDataGateway_Missing_TableAttribute {
            get {
                return ResourceManager.GetString("RowDataGateway_Missing_TableAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column {0} cannot be null.
        /// </summary>
        internal static string RowDataGateway_Null_Column {
            get {
                return ResourceManager.GetString("RowDataGateway_Null_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} does not accept null value.
        /// </summary>
        internal static string RowDataGateway_Null_Property {
            get {
                return ResourceManager.GetString("RowDataGateway_Null_Property", resourceCulture);
            }
        }
    }
}
