//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace VB.Reports.App.ReportDefinitionLibrary.Xml.Serialization
{
    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.42.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://tempuri.org/ReportGroupingMetadata.xsd")]
    [XmlRoot(Namespace = "http://tempuri.org/ReportGroupingMetadata.xsd", IsNullable = false)]
    public partial class ReportReference
    {

        private bool comingSoonField;

        private bool comingSoonFieldSpecified;

        private string valueField;

        /// <remarks/>
        [XmlAttribute()]
        public bool ComingSoon
        {
            get
            {
                return this.comingSoonField;
            }
            set
            {
                this.comingSoonField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool ComingSoonSpecified
        {
            get
            {
                return this.comingSoonFieldSpecified;
            }
            set
            {
                this.comingSoonFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlText(DataType = "IDREF")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://tempuri.org/ReportGroupingMetadata.xsd")]
    [XmlRoot(Namespace = "http://tempuri.org/ReportGroupingMetadata.xsd", IsNullable = false)]
    public partial class Content
    {

        private object[] itemsField;

        /// <remarks/>
        [XmlElement("Node", typeof(Node))]
        [XmlElement("ReportReference", typeof(ReportReference))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://tempuri.org/ReportGroupingMetadata.xsd")]
    [XmlRoot(Namespace = "http://tempuri.org/ReportGroupingMetadata.xsd", IsNullable = false)]
    public partial class Node
    {

        private string titleField;

        private string descriptionField;

        private Content contentField;

        private string idField;

        private NodeType nodeTypeField;

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public Content Content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public NodeType NodeType
        {
            get
            {
                return this.nodeTypeField;
            }
            set
            {
                this.nodeTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [XmlType(Namespace = "http://tempuri.org/ReportGroupingMetadata.xsd")]
    public enum NodeType
    {

        /// <remarks/>
        ReportGroup,

        /// <remarks/>
        ReportHandle,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://tempuri.org/ReportGroupingMetadata.xsd")]
    [XmlRoot("ReportGroupings", Namespace = "http://tempuri.org/ReportGroupingMetadata.xsd", IsNullable = false)]
    public partial class ReportGrouping
    {

        private Node nodeField;

        private string idField;

        private ReportGroupingType reportGroupingTypeField;

        /// <remarks/>
        public Node Node
        {
            get
            {
                return this.nodeField;
            }
            set
            {
                this.nodeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public ReportGroupingType ReportGroupingType
        {
            get
            {
                return this.reportGroupingTypeField;
            }
            set
            {
                this.reportGroupingTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [XmlType(Namespace = "http://tempuri.org/ReportGroupingMetadata.xsd")]
    public enum ReportGroupingType
    {

        /// <remarks/>
        Dealer,

        /// <remarks/>
        DealerGroup,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://tempuri.org/ReportGroupingMetadata.xsd")]
    [XmlRoot(Namespace = "http://tempuri.org/ReportGroupingMetadata.xsd", IsNullable = false)]
    public partial class ReportGroupingMetadata
    {

        private ReportGrouping[] reportGroupingsField;

        /// <remarks/>
        [XmlElement("ReportGroupings")]
        public ReportGrouping[] ReportGroupings
        {
            get
            {
                return this.reportGroupingsField;
            }
            set
            {
                this.reportGroupingsField = value;
            }
        }
    }
}