//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

namespace VB.Reports.App.ReportDefinitionLibrary.Xml.Serialization
{
// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
[XmlRoot(Namespace="http://tempuri.org/ReportMetadata.xsd", IsNullable=false)]
public partial class Authorization {
    
    private string[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    /// <remarks/>
    [XmlElement("Allow", typeof(string))]
    [XmlElement("Deny", typeof(string))]
    [XmlChoiceIdentifier("ItemsElementName")]
    public string[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("ItemsElementName")]
    [XmlIgnore()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd", IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    Allow,
    
    /// <remarks/>
    Deny,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
public partial class SelectedDomainValue {
    
    private string indexField;
    
    private string valueField;
    
    /// <remarks/>
    [XmlAttribute(DataType="integer")]
    public string Index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
public partial class InsertDomainValues {
    
    private ParameterValue[] parameterValueField;
    
    private string indexField;
    
    /// <remarks/>
    [XmlElement("ParameterValue")]
    public ParameterValue[] ParameterValue {
        get {
            return this.parameterValueField;
        }
        set {
            this.parameterValueField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="integer")]
    public string Index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
public partial class CustomDomainValues {
    
    private InsertDomainValues insertField;
    
    /// <remarks/>
    public InsertDomainValues Insert {
        get {
            return this.insertField;
        }
        set {
            this.insertField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
public partial class DomainModelMember {
    
    private MemberType memberTypeField;
    
    private string nameField;
    
    /// <remarks/>
    [XmlAttribute()]
    public MemberType MemberType {
        get {
            return this.memberTypeField;
        }
        set {
            this.memberTypeField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
public enum MemberType {
    
    /// <remarks/>
    Field,
    
    /// <remarks/>
    Property,
    
    /// <remarks/>
    Method,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
public partial class MethodArgument {
    
    private string valueField;
    
    private string nameField;
    
    private string typeField;
    
    private MethodArgumentSource sourceField;
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public MethodArgumentSource Source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
public enum MethodArgumentSource {
    
    /// <remarks/>
    Callback,
    
    /// <remarks/>
    Constant,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
public partial class InvokeMethod {
    
    private string methodNameField;
    
    private MethodArgument[] argumentsField;
    
    /// <remarks/>
    public string MethodName {
        get {
            return this.methodNameField;
        }
        set {
            this.methodNameField = value;
        }
    }
    
    /// <remarks/>
    [XmlArrayItem("Argument", IsNullable=false)]
    public MethodArgument[] Arguments {
        get {
            return this.argumentsField;
        }
        set {
            this.argumentsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
[XmlRoot(Namespace="http://tempuri.org/ReportMetadata.xsd", IsNullable=false)]
public partial class LocalReport {
    
    private string fileField;
    
    private string dataSourceNameField;
    
    /// <remarks/>
    public string File {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
        }
    }
    
    /// <remarks/>
    public string DataSourceName {
        get {
            return this.dataSourceNameField;
        }
        set {
            this.dataSourceNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
[XmlRoot(Namespace="http://tempuri.org/ReportMetadata.xsd", IsNullable=false)]
public partial class ServerReport {
    
    private string pathField;
    
    /// <remarks/>
    [XmlElement(DataType="anyURI")]
    public string Path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
[XmlRoot(Namespace="http://tempuri.org/ReportMetadata.xsd", IsNullable=false)]
public partial class ReportProcessingLocation {
    
    private LocalReport localReportField;
    
    private ServerReport serverReportField;
    
    private ActiveReportProcessingLocation useField;
    
    public ReportProcessingLocation() {
        this.useField = ActiveReportProcessingLocation.LocalReport;
    }
    
    /// <remarks/>
    public LocalReport LocalReport {
        get {
            return this.localReportField;
        }
        set {
            this.localReportField = value;
        }
    }
    
    /// <remarks/>
    public ServerReport ServerReport {
        get {
            return this.serverReportField;
        }
        set {
            this.serverReportField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    [System.ComponentModel.DefaultValueAttribute(ActiveReportProcessingLocation.LocalReport)]
    public ActiveReportProcessingLocation Use {
        get {
            return this.useField;
        }
        set {
            this.useField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
public enum ActiveReportProcessingLocation {
    
    /// <remarks/>
    LocalReport,
    
    /// <remarks/>
    ServerReport,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
[XmlRoot(Namespace="http://tempuri.org/ReportMetadata.xsd", IsNullable=false)]
public partial class ParameterValue {
    
    private string valueField;
    
    private string labelField;
    
    private bool selectedField;
    
    public ParameterValue() {
        this.selectedField = false;
    }
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    public string Label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Selected {
        get {
            return this.selectedField;
        }
        set {
            this.selectedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
[XmlRoot(Namespace="http://tempuri.org/ReportMetadata.xsd", IsNullable=false)]
public partial class ParameterValues {
    
    private ParameterValue[] parameterValueField;
    
    /// <remarks/>
    [XmlElement("ParameterValue")]
    public ParameterValue[] ParameterValue {
        get {
            return this.parameterValueField;
        }
        set {
            this.parameterValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
[XmlRoot(Namespace="http://tempuri.org/ReportMetadata.xsd", IsNullable=false)]
public partial class DateTimeFormatInfo {
    
    private string fullDateTimePatternField;
    
    private string longDatePatternField;
    
    private string longTimePatternField;
    
    private string monthDayPatternField;
    
    private string shortDatePatternField;
    
    private string shortTimePatternField;
    
    private string yearMonthPatternField;
    
    /// <remarks/>
    public string FullDateTimePattern {
        get {
            return this.fullDateTimePatternField;
        }
        set {
            this.fullDateTimePatternField = value;
        }
    }
    
    /// <remarks/>
    public string LongDatePattern {
        get {
            return this.longDatePatternField;
        }
        set {
            this.longDatePatternField = value;
        }
    }
    
    /// <remarks/>
    public string LongTimePattern {
        get {
            return this.longTimePatternField;
        }
        set {
            this.longTimePatternField = value;
        }
    }
    
    /// <remarks/>
    public string MonthDayPattern {
        get {
            return this.monthDayPatternField;
        }
        set {
            this.monthDayPatternField = value;
        }
    }
    
    /// <remarks/>
    public string ShortDatePattern {
        get {
            return this.shortDatePatternField;
        }
        set {
            this.shortDatePatternField = value;
        }
    }
    
    /// <remarks/>
    public string ShortTimePattern {
        get {
            return this.shortTimePatternField;
        }
        set {
            this.shortTimePatternField = value;
        }
    }
    
    /// <remarks/>
    public string YearMonthPattern {
        get {
            return this.yearMonthPatternField;
        }
        set {
            this.yearMonthPatternField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
[XmlRoot(Namespace="http://tempuri.org/ReportMetadata.xsd", IsNullable=false)]
public partial class DateRange {
    
    private DateTimeFormatInfo dateTimeFormatInfoField;
    
    private TimeUnit initialUnitField;
    
    private string initialDistanceField;
    
    private TimeUnit distanceUnitField;
    
    private string distanceField;
    
    private string numberOfItemsField;
    
    private TimeDirection directionField;
    
    private string selectedIndexField;
    
    private DateTimeFormatSpecifier labelDateTimeFormatSpecifierField;
    
    private DateTimeFormatSpecifier valueDateTimeFormatSpecifierField;
    
    public DateRange() {
        this.initialDistanceField = "0";
        this.distanceField = "1";
        this.selectedIndexField = "0";
    }
    
    /// <remarks/>
    public DateTimeFormatInfo DateTimeFormatInfo {
        get {
            return this.dateTimeFormatInfoField;
        }
        set {
            this.dateTimeFormatInfoField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public TimeUnit InitialUnit {
        get {
            return this.initialUnitField;
        }
        set {
            this.initialUnitField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("0")]
    public string InitialDistance {
        get {
            return this.initialDistanceField;
        }
        set {
            this.initialDistanceField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public TimeUnit DistanceUnit {
        get {
            return this.distanceUnitField;
        }
        set {
            this.distanceUnitField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string Distance {
        get {
            return this.distanceField;
        }
        set {
            this.distanceField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="integer")]
    public string NumberOfItems {
        get {
            return this.numberOfItemsField;
        }
        set {
            this.numberOfItemsField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public TimeDirection Direction {
        get {
            return this.directionField;
        }
        set {
            this.directionField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="integer")]
    [System.ComponentModel.DefaultValueAttribute("0")]
    public string SelectedIndex {
        get {
            return this.selectedIndexField;
        }
        set {
            this.selectedIndexField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    [CLSCompliant(false)]
    public DateTimeFormatSpecifier LabelDateTimeFormatSpecifier {
        get {
            return this.labelDateTimeFormatSpecifierField;
        }
        set {
            this.labelDateTimeFormatSpecifierField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    [CLSCompliant(false)]
    public DateTimeFormatSpecifier ValueDateTimeFormatSpecifier {
        get {
            return this.valueDateTimeFormatSpecifierField;
        }
        set {
            this.valueDateTimeFormatSpecifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
public enum TimeUnit {
    
    /// <remarks/>
    YY,
    
    /// <remarks/>
    MM,
    
    /// <remarks/>
    DD,
    
    /// <remarks/>
    HH,
    
    /// <remarks/>
    MI,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
public enum TimeDirection {
    
    /// <remarks/>
    Backward,
    
    /// <remarks/>
    Forward,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
[CLSCompliant(false)]
public enum DateTimeFormatSpecifier {
    
    /// <remarks/>
    d,
    
    /// <remarks/>
    D,
    
    /// <remarks/>
    t,
    
    /// <remarks/>
    T,
    
    /// <remarks/>
    f,
    
    /// <remarks/>
    F,
    
    /// <remarks/>
    g,
    
    /// <remarks/>
    G,
    
    /// <remarks/>
    M,
    
    /// <remarks/>
    m,
    
    /// <remarks/>
    R,
    
    /// <remarks/>
    r,
    
    /// <remarks/>
    s,
    
    /// <remarks/>
    u,
    
    /// <remarks/>
    U,
    
    /// <remarks/>
    Y,
    
    /// <remarks/>
    y,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
[XmlRoot(Namespace="http://tempuri.org/ReportMetadata.xsd", IsNullable=false)]
public partial class ParameterRange {
    
    private DateRange itemField;
    
    /// <remarks/>
    [XmlElement("DateRange")]
    public DateRange Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
[XmlRoot(Namespace="http://tempuri.org/ReportMetadata.xsd", IsNullable=false)]
public partial class DomainModel {
    
    private string domainModelNameField;
    
    private InvokeMethod invokeMethodField;
    
    private DomainModelMember labelField;
    
    private DomainModelMember valueField;
    
    private CustomDomainValues customValuesField;
    
    private SelectedDomainValue selectedField;
    
    /// <remarks/>
    public string DomainModelName {
        get {
            return this.domainModelNameField;
        }
        set {
            this.domainModelNameField = value;
        }
    }
    
    /// <remarks/>
    public InvokeMethod InvokeMethod {
        get {
            return this.invokeMethodField;
        }
        set {
            this.invokeMethodField = value;
        }
    }
    
    /// <remarks/>
    public DomainModelMember Label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    public DomainModelMember Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    public CustomDomainValues CustomValues {
        get {
            return this.customValuesField;
        }
        set {
            this.customValuesField = value;
        }
    }
    
    /// <remarks/>
    public SelectedDomainValue Selected {
        get {
            return this.selectedField;
        }
        set {
            this.selectedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
[XmlRoot(Namespace="http://tempuri.org/ReportMetadata.xsd", IsNullable=false)]
public partial class ValidValues {
    
    private object itemField;
    
    /// <remarks/>
    [XmlElement("DomainModel", typeof(DomainModel))]
    [XmlElement("ParameterRange", typeof(ParameterRange))]
    [XmlElement("ParameterValues", typeof(ParameterValue[]))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
[XmlRoot(Namespace="http://tempuri.org/ReportMetadata.xsd", IsNullable=false)]
public partial class Parameter {
    
    private string nameField;
    
    private string labelField;
    
    private ValidValues validValuesField;
    
    private ParameterDataType parameterDataTypeField;
    
    private ParameterInputType parameterInputTypeField;
    
    private bool allowNullField;
    
    private bool allowBlankField;
    
    public Parameter() {
        this.allowNullField = false;
        this.allowBlankField = false;
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    public ValidValues ValidValues {
        get {
            return this.validValuesField;
        }
        set {
            this.validValuesField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public ParameterDataType ParameterDataType {
        get {
            return this.parameterDataTypeField;
        }
        set {
            this.parameterDataTypeField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public ParameterInputType ParameterInputType {
        get {
            return this.parameterInputTypeField;
        }
        set {
            this.parameterInputTypeField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool AllowNull {
        get {
            return this.allowNullField;
        }
        set {
            this.allowNullField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool AllowBlank {
        get {
            return this.allowBlankField;
        }
        set {
            this.allowBlankField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
public enum ParameterDataType {
    
    /// <remarks/>
    Boolean,
    
    /// <remarks/>
    DateTime,
    
    /// <remarks/>
    Integer,
    
    /// <remarks/>
    Float,
    
    /// <remarks/>
    String,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
public enum ParameterInputType {
    
    /// <remarks/>
    Text,
    
    /// <remarks/>
    Password,
    
    /// <remarks/>
    Checkbox,
    
    /// <remarks/>
    Radio,
    
    /// <remarks/>
    Hidden,
    
    /// <remarks/>
    Select,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
[XmlRoot(Namespace="http://tempuri.org/ReportMetadata.xsd", IsNullable=false)]
public partial class Parameters {
    
    private Parameter[] parameterField;
    
    /// <remarks/>
    [XmlElement("Parameter")]
    public Parameter[] Parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
[XmlRoot(Namespace="http://tempuri.org/ReportMetadata.xsd", IsNullable=false)]
public partial class Report {
    
    private string nameField;
    
    private string descriptionField;
    
    private ReportProcessingLocation reportProcessingLocationField;
    
    private Parameter[] parametersField;
    
    private Authorization authorizationField;
    
    private string idField;
    
    private ReportType reportTypeField;
    
    private System.DateTime newUntilField;
    
    private bool newUntilFieldSpecified;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public ReportProcessingLocation ReportProcessingLocation {
        get {
            return this.reportProcessingLocationField;
        }
        set {
            this.reportProcessingLocationField = value;
        }
    }
    
    /// <remarks/>
    [XmlArrayItem(IsNullable=false)]
    public Parameter[] Parameters {
        get {
            return this.parametersField;
        }
        set {
            this.parametersField = value;
        }
    }
    
    /// <remarks/>
    public Authorization Authorization {
        get {
            return this.authorizationField;
        }
        set {
            this.authorizationField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="ID")]
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public ReportType ReportType {
        get {
            return this.reportTypeField;
        }
        set {
            this.reportTypeField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="date")]
    public System.DateTime NewUntil {
        get {
            return this.newUntilField;
        }
        set {
            this.newUntilField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool NewUntilSpecified {
        get {
            return this.newUntilFieldSpecified;
        }
        set {
            this.newUntilFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[Serializable()]
[XmlType(Namespace="http://tempuri.org/ReportMetadata.xsd")]
public enum ReportType {
    
    /// <remarks/>
    Dealer,
    
    /// <remarks/>
    DealerGroup,
}

/// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://tempuri.org/ReportMetadata.xsd")]
    [XmlRoot(Namespace = "http://tempuri.org/ReportMetadata.xsd", IsNullable = false)]
    public partial class ReportMetadata
    {

        private Report[] reportField;

        /// <remarks/>
        [XmlElement("Report")]
        public Report[] Report
        {
            get
            {
                return this.reportField;
            }
            set
            {
                this.reportField = value;
            }
        }
    }
}
