//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 

using System.Xml.Serialization;

namespace BV.DomainModel.SoftwareSystem.Xml {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://tempuri.org/WebResourceRegistry.xsd")]
    [XmlRoot(Namespace="http://tempuri.org/WebResourceRegistry.xsd", IsNullable=false)]
    public partial class Page {
        
        private string pathField;
        
        private OnError onErrorField;
        
        private string targetField;
        
        public Page() {
            this.onErrorField = OnError.Close;
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(OnError.Close)]
        public OnError OnError {
            get {
                return this.onErrorField;
            }
            set {
                this.onErrorField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [XmlType(Namespace="http://tempuri.org/WebResourceRegistry.xsd")]
    public enum OnError {
        
        /// <remarks/>
        Close,
        
        /// <remarks/>
        Page,
        
        /// <remarks/>
        Home,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://tempuri.org/WebResourceRegistry.xsd")]
    [XmlRoot(Namespace="http://tempuri.org/WebResourceRegistry.xsd", IsNullable=false)]
    public partial class SoftwareSystemComponent {
        
        private Page[] pageField;
        
        private string nameField;
        
        private string homeField;
        
        /// <remarks/>
        [XmlElement("Page")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Justification = "XML Serialization Pattern")]
        public Page[] Page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string Home {
            get {
                return this.homeField;
            }
            set {
                this.homeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://tempuri.org/WebResourceRegistry.xsd")]
    [XmlRoot(Namespace="http://tempuri.org/WebResourceRegistry.xsd", IsNullable=false)]
    public partial class WebResourceRegistry {
        
        private SoftwareSystemComponent[] softwareSystemComponentField;
        
        /// <remarks/>
        [XmlElement("SoftwareSystemComponent")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Justification = "XML Serialization Pattern")]
        public SoftwareSystemComponent[] SoftwareSystemComponent {
            get {
                return this.softwareSystemComponentField;
            }
            set {
                this.softwareSystemComponentField = value;
            }
        }
    }
}
